### ISSUE TITLE
Unable to resolve some modules: MarkerClusterer

### ISSUE THREAD

**Issue by zhukovsp** [Akryum/vue-meteor-demo#17]
When I run 
```meteor```
I get
```=> Exited with code: 1
Unable to resolve some modules:
 "MarkerClusterer" ...
If you notice problems related to these missing modules, consider running:
  meteor npm install --save MarkerClusterer
```
When I run
```meteor npm install --save MarkerClusterer```
I get
```npm ERR! code E404
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/MarkerClusterer
npm ERR! 404 
npm ERR! 404  'MarkerClusterer' is not in the npm registry.
```
Even if I run from the [doc](https://github.com/xkjyeah/vue-google-maps/blob/vue2/API.md#cluster-class-mixes-in-mapelementmixin)
``` meteor npm install --save  marker-clusterer-plus```
I get first error

**Comment by thearabbit** [comment]
I got the same, It has problem with `Vue Google Map Package`

**Comment by thearabbit** [comment]
Very thanks 💯
