### ISSUE TITLE
What is the expected behavior of the SSR version of the code?

### ISSUE THREAD

**Issue by gustojs** [Akryum/vue-meteor-demo#2]
Just to clarify few things so we can properly test everything. Let's say I add a setTimeout with 60 seconds to the client code and I have time to play with SSR version for a minute.

What is the expected behavior of the SSR version, what should actually be working and what should not?

1) Switching routes - clicking a link makes a new request and as the client loads from 0, setTimeout starts from 0 too. I guess that's just how SSR works and there's no workaround possible.

2) Adding a new note - pressing enter doesn't create new note. I guess it's just an HTML file with no user interaction?

3) After the client actually loads, it resets the value of the input field. Is the user supposed to wait with such interaction until the client code loads? (which usually should happen pretty fast)

**Comment by Akryum** [comment]
1) Correct
2) Yes, there is no interaction since the JavaScript code is not loaded yet. Time to interaction can be better with code-splitting.
3) Maybe this could be improved in Vue.

**Comment by gustojs** [comment]
Thanks a lot. :)
