### ISSUE TITLE
Cannot install this project

### ISSUE THREAD

**Issue by EMHmark7** [Akryum/vue-meteor-demo#24]
After cloning:

F:\meteor-sites\vue-meteor-demo>meteor npm i
npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Marc\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-o
s.windows.x86_32\dev_bundle\.npm\_logs\2018-02-26T23_02_44_708Z-debug.log

F:\meteor-sites\vue-meteor-demo>

**Comment by Akryum** [comment]
Try adding the git binary into your PATH environment variable.

**Comment by JasonOry** [comment]
It worked for me by opening git-cmd going to the correct app location, THEN running "meteor npm install". NOTE: I also added git bin to my path don't know if that had to be done too. I forgot to remove it after trying something else.
