### ISSUE TITLE
errors on install

### ISSUE THREAD

**Issue by waelio** [Akryum/vue-meteor-demo#27]
Straight outa the box:
Waels-iMac:vmi waelio$ meteor
[[[[[ /Library/WebServer/Documents/vmi ]]]]]  

=> Started proxy.                             
=> [HMR] Dev server listening on port 3003.
=> Errors prevented startup:                  
   
   While building for web.browser:
   src/imports/ui/App.vue:1: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/Home.vue:31: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/Notes.vue:99: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/NotesComponents.vue:86: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/NotesComputed.vue:94: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/GoogleMap.vue:29: [vue-component] Error while compiling in tag <script> using lang coffee [vue-component] Error while compiling in tag <script> using lang coffee: Can't find handler for lang 'coffee', did you install it?
   src/imports/ui/Apollo.vue:36: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/About.vue:36: [vue-component] Error while compiling in tag <style> using lang scss [vue-component] Error while compiling in tag <style> using lang scss: Can't find handler for lang 'scss', did you install it?
   
   While building for web.browser.legacy:
   src/imports/ui/App.vue:1: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/Home.vue:31: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/Notes.vue:99: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/NotesComponents.vue:86: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/NotesComputed.vue:94: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/GoogleMap.vue:29: [vue-component] Error while compiling in tag <script> using lang coffee [vue-component] Error while compiling in tag <script> using lang coffee: Can't find handler for lang 'coffee', did you install it?
   src/imports/ui/Apollo.vue:36: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/About.vue:36: [vue-component] Error while compiling in tag <style> using lang scss [vue-component] Error while compiling in tag <style> using lang scss: Can't find handler for lang 'scss', did you install it?
   
   While building for os.osx.x86_64:
   src/imports/ui/App.vue:1: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/Home.vue:31: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/Notes.vue:99: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/NotesComponents.vue:86: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/NotesComputed.vue:94: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/GoogleMap.vue:29: [vue-component] Error while compiling in tag <script> using lang coffee [vue-component] Error while compiling in tag <script> using lang coffee: Can't find handler for lang 'coffee', did you install it?
   src/imports/ui/Apollo.vue:36: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/About.vue:36: [vue-component] Error while compiling in tag <style> using lang scss [vue-component] Error while compiling in tag <style> using lang scss: Can't find handler for lang 'scss', did you install it?
   
=> Your application has errors. Waiting for file change.
=> Started MongoDB.

**Comment by cswww** [comment]
=> Errors prevented startup:                  
   
   While building for web.browser:
   src/imports/ui/App.vue:1: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/Home.vue:31: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/Notes.vue:99: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/NotesComponents.vue:86: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/NotesComputed.vue:94: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/GoogleMap.vue:29: [vue-component] Error while compiling in tag <script> using lang coffee [vue-component] Error while compiling in tag <script> using lang coffee: Can't find handler for lang 'coffee', did you install it?
   src/imports/ui/Apollo.vue:36: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/About.vue:36: [vue-component] Error while compiling in tag <style> using lang scss [vue-component] Error while compiling in tag <style> using lang scss: Can't find handler for lang 'scss', did you install it?
   
   While building for web.browser.legacy:
   src/imports/ui/App.vue:1: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/Home.vue:31: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/Notes.vue:99: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/NotesComponents.vue:86: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/NotesComputed.vue:94: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/GoogleMap.vue:29: [vue-component] Error while compiling in tag <script> using lang coffee [vue-component] Error while compiling in tag <script> using lang coffee: Can't find handler for lang 'coffee', did you install it?
   src/imports/ui/Apollo.vue:36: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/About.vue:36: [vue-component] Error while compiling in tag <style> using lang scss [vue-component] Error while compiling in tag <style> using lang scss: Can't find handler for lang 'scss', did you install it?
   
   While building for os.osx.x86_64:
   src/imports/ui/App.vue:1: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/Home.vue:31: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/Notes.vue:99: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/NotesComponents.vue:86: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/NotesComputed.vue:94: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/GoogleMap.vue:29: [vue-component] Error while compiling in tag <script> using lang coffee [vue-component] Error while compiling in tag <script> using lang coffee: Can't find handler for lang 'coffee', did you install it?
   src/imports/ui/Apollo.vue:36: [vue-component] Error while compiling in tag <style> using lang less [vue-component] Error while compiling in tag <style> using lang less: Can't find handler for lang 'less', did you install it?
   src/imports/ui/About.vue:36: [vue-component] Error while compiling in tag <style> using lang scss [vue-component] Error while compiling in tag <style> using lang scss: Can't find handler for lang 'scss', did you install it?
   
=> Your application has errors. Waiting for file change.
=> Started MongoDB.

**Comment by MichaelJCole** [comment]
@waelio This worked for me on Ubuntu 18.04:

```
git clone git@github.com:meteor-vue/vue-meteor-demo.git 
cd vue-meteor-demo     
meteor npm install 
meteor
```
It should look like this:
```
michael@mc-desktop ~/scm/vue-meteor-demo
☀  meteor                                                                                                                                                                                               Mod master
[[[[[ ~/scm/vue-meteor-demo ]]]]]             

=> Started proxy.                             
=> A patch (Meteor 1.6.1.3) for your current release is available!
   Update this project now with 'meteor update --patch'.
=> Started MongoDB.                           
=> [HMR] Dev server listening on port 3003.
I20180623-10:21:30.040(-7)? tracker installed 
=> Started your app.

=> App running at: http://localhost:3000/
I20180623-10:21:45.801(-7)? [SSR] Data prefetch: 26ms
```
I think you forgot to `meteor npm install`  That's part of how meteor works.

https://guide.meteor.com/using-npm-packages.html

**Comment by cswww** [comment]
Yes, thank you.
