### ISSUE TITLE
[TypeError: Cannot read property 'exportNamespace' of undefined]

### ISSUE THREAD

**Issue by nilsi** [Akryum/vue-meteor-demo#9]
After cloning and installing dependencies Im getting this error:

```
$ meteor
[[[[[ ~/Documents/repos/vue-meteor-demo ]]]]] 

=> Started proxy.                             
=> Started MongoDB.                           
   [HMR] Dev server listening on port 3003
I20170803-10:42:44.434(2)? tracker installed  
=> Started your app.

=> App running at: http://localhost:3000/
I20170803-10:43:09.988(2)? data pre-fetch: 48ms
W20170803-10:43:09.991(2)? (STDERR) [TypeError: Cannot read property 'exportNamespace' of undefined]
```
Didn't have the time to research exactly whats causing it.

**Comment by sdarnell** [comment]
I'm getting the same. Seems to be related to Apollo, but without a stack trace its a bit tricky, but there seems to be only a few references.
Looks like it might be the code below:
```
var states = this.getStates({
        exportNamespace: options.exportNamespace
      });
```
Unlike the 'getStates', 'exportStates' doesn't seem to verify that options has an exportNamespace

**Comment by AsafAgranat** [comment]
Happening here too. Can't get the app running because of this.

**Comment by Akryum** [comment]
Please update to the latest vue-apollo version. :smile:

**Comment by sdarnell** [comment]
Thanks for the quick update - it works for me now :)

Oddly, there's an error/warning in the chrome devtools for the top level component (even after a meteor reset and restart + new window) - but this is unrelated.
```
DevTools failed to parse SourceMap: http://localhost:3000/About.vue.css.map
```
